### ISSUE TITLE
Support for DoubleFloats

### ISSUE THREAD

**Issue by VinTz1** [JuliaComputing/FourierTransforms.jl#12]
Hello,

I was trying this package and I noticed that Double64 type provided by DoubleFloats is not supported. Is there a plan to add support for this in the future?

Best regards

**Comment by VinTz1** [comment]
I figured out that FourierTransforms.fft(Complex{Double64}.(...)) works. I will continue testing this.

**Comment by mfherbst** [comment]
Yes, it compiles and runs, but notice, that for some sizes of the input array the results are currently not correct (see #10).
